### ISSUE TITLE
SSL issues with Cloudflare

### ISSUE THREAD

**Issue by ahmadnassri** [APIAnalytics/HARchiver#8]
issue reported by user through support channel:

```
Hi, I'm having some trouble setting up the harchiver proxy. 

I'm using Cloudflares Flexible SSL configuration, which says that the connection is encrypted from browser <-> cloudflare but not from cloudflare <-> my own server.

On my own server i have running

sudo ./harchiver 80 -reverse 127.0.0.1:81 xxxx 
running, which works fine for http traffic. I can see the endpoints working fine.

 but when i try https:// traffic, it gives a SSL configuration error.

However the connection should be totally unencrypted since cloudflare says it connection from cloudflare to webserver is unencrypted but harchive freaks out and complains out a SSL configuration error 504.

Any help would be appreciated 
```

**Comment by FaisalAbid** [comment]
Hi @SGrondin i'm the one who reported this, please let me know if you want any more details. Thanks

**Comment by FaisalAbid** [comment]
Hey, Any update?

**Comment by iangcarroll** [comment]
I had a similar issue (the same?) which was fixed by adding `proxy_set_header Mashape-Upstream-Protocol "HTTP";` in my nginx location block. My setup is `nginx -> HARchiver -> nginx`, so I just added it to the first `nginx` listener. 

It seems HARchiver tries to connect via TLS to the host it's proxying if the request was made via TLS, but it shouldn't be doing this when it's not the one terminating the TLS connection.

**Comment by SGrondin** [comment]
HARchiver will be getting a big upgrade in the next few weeks to address a few issues, including those mentioned here.

**Comment by FaisalAbid** [comment]
Thanks

**Comment by FaisalAbid** [comment]
Was this ever resolved?

**Comment by SGrondin** [comment]
HARchiver has been completely deprecated. We suggest using one of our agents (including for Node.js, Java and others) or [Kong](http://getkong.org/).
